title: UniversalBit
description: keep calm and make something of amazing
logo: /assets/img/logo.png
show_downloads: false
google_analytics: G-MN27QKSXPR
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
plugins:
- "jekyll-feed"
- "jekyll-seo-tag"
- "jekyll-remote-theme"
- "jekyll-redirect-from"
- "jekyll-coffeescript"
- "jekyll-github-metadata"
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
noscript: false
kramdown:
math_engine: mathjax
syntax_highlighter: rouge
