title: UniversalBit
description: keep calm and make something of amazing
logo: /assets/img/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: /
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
noscript: false
kramdown:
math_engine: mathjax
syntax_highlighter: rouge
