domain: universalbit.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://universalbit.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /universalbit.github.io/  # place folder name if the site is served in a subfolder

title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
